### ISSUE TITLE
Simplifying brackets

### ISSUE THREAD

**Issue by mikaelho** [SonOfLilit/kleenexp#31]
Could we get rid of the inner brackets in something like `[0+ [#letter | #digit]]`? It seems that the first operator should be discernible as such, without having to require the extra brackets around the "either".

Asking before spending time on a PR, as you might have fought this battle already, and come away bloody.

**Comment by SonOfLilit** [comment]
It's easy to do technically, but I'm afraid of the ambiguity between `[1+
['A' | 'B']]` and `[[1+ 'A'] | 'B']` will confound newcomers. Do you think
it's extremely clear that it's always the first?

**Comment by SonOfLilit** [comment]
Having put more thought into it and talked to a beginner, I still think the confusion causes more harm than the saving of a few keystrokes causes good. Marking WONTFIX.

**Comment by mikaelho** [comment]
Thank you for taking the time to consider it. 👍🏻
