### ISSUE TITLE
Syntax suggestion: Baseline capture group

### ISSUE THREAD

**Issue by mikaelho** [SonOfLilit/kleenexp#32]
`[capture:name]` expands behind the scenes to `[capture:name 1+ #any]`.

**Comment by SonOfLilit** [comment]
I really believe that explicit is better than implicit.

**Comment by mikaelho** [comment]
That is perfectly understandable. 👍🏼 ... Although, in this case, I would not consider this any more implicit than default values for keyword parameters.
